baseurl = "https://openmobility.eclipse.org/"
DefaultContentLanguage = "en"
title = "The openMobility working group will drive the evolution and broad adoption of mobility modelling and simulation technologies." 
theme = "eclipsefdn-hugo-solstice-theme"
metaDataFormat = "yaml"
#googleAnalytics = ""
disableKinds = ["taxonomyTerm"]
themesDir = "node_modules/"
buildFuture = true #allows to publish posts with future dates
canonifyURLs = false #keep false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Params]
  google_tag_manager = "GTM-5WLCZXC"
  description = "The openMobility working group will drive the evolution and broad adoption of mobility modelling and simulation technologies."
  subtitle = ""
  seo_title_suffix = " | Eclipse openMobility Working Group | The Eclipse Foundation"
  keywords = ["Mobility modelling", "simulation technologies", "OpenMobility framework", "Mobility-as-a-Service"]
  logo = "images/logo/logo.svg"
  styles = "css/styles.css"
  favicon = "images/favicon.png"
  share_img = "images/share-image.png"
  gcse = "011805775785170369411:p3ec0igo0qq"
# subtheme = ""
  header_wrapper_class = "header-default-bg-img"
  js = "js/solstice.js"
  featured_content_publish_target = "openmobility"
# call_for_action_text = ""
# call_for_action_url = ""
# call_for_action_icon = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[Author]
  name = "Christopher Guindon"
  website = "https://www.eclipse.org"
  email = "chris.guindon@eclipse-foundation.org"
  facebook = "eclipse.org"
  twitter = "EclipseFdn"
  youtube = "EclipseFdn"
  googleplus = "+Eclipse"
  linkedin = "company/eclipse-foundation/"

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "News"
    url = "/news/"
    weight = 2

[[menu.main]]
    name = "Events"
    url = "/events/"
    weight = 3

[[menu.main]]
    name = "Vision"
    url = "/vision/"
    weight = 4

[[menu.main]]
    name = "Technologies"
    url = "/technologies/"
    weight = 5

[[menu.main]]
    name = "Members"
    url = "/members/"
    weight = 6

[[menu.main]]
    name = "Working Group"
    url = "/working-group/"
    weight = 7

# Sub-menu

[[menu.main]]
    name = "Eclipse SUMO"
    url = "/technologies/eclipse-sumo"
    parent = "Technologies"
    weight = 1

[[menu.main]]
    name = "Eclipse MOSAIC"
    url = "/technologies/eclipse-mosaic"
    parent = "Technologies"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/working-group/"
    parent = "Working Group"
    weight = 1

[[menu.main]]
    name = "Charter"
    url = "https://www.eclipse.org/org/workinggroups/openmobility_charter.php"
    parent = "Working Group"
    weight = 2

[[menu.main]]
    name = "Join Eclipse openMobility"
    url = "/working-group/become-a-member"
    parent = "Working Group"
    weight = 3

[[menu.main]]
    name = "User Stories"
    url = "https://github.com/openmobility-wg/userstories/issues"
    parent = "Working Group"
    weight = 4

[[menu.main]]
    name = "Meeting Minutes"
    url = "https://wiki.eclipse.org/OpenMobilityMeetingMinutes"
    parent = "Working Group"
    weight = 5

[[menu.main]]
    name = "Contact"
    url = "/working-group/contact"
    parent = "Working Group"
    weight = 6
