baseurl = "https://openmobility.eclipse.org/"
DefaultContentLanguage = "en"
title = "The OpenMobility working group will drive the evolution and broad adoption of mobility modelling and simulation technologies." 
theme = "eclipsefdn-hugo-solstice-theme"
metaDataFormat = "yaml"
#googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]
themesDir = "node_modules/"

[Params]
  google_tag_manager = "GTM-5WLCZXC"
  description = ""
  subtitle = ""
  seo_title_suffix = "| Eclipse OpenMobility Working Group | The Eclipse Foundation"
  keywords = ["Mobility modelling", "simulation technologies", "OpenMobility framework", "Mobility-as-a-Service"]
# logo = ""
# styles = "css/styles.css"
# favicon = "o"
# share_img = ""
  gcse = "011805775785170369411:p3ec0igo0qq"
# subtheme = ""
  header_wrapper_class = "header-default-bg-img"
# js = "js/solstice.js"
# call_for_action_text = ""
# call_for_action_url = ""
# call_for_action_icon = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[Author]
  name = "Christopher Guindon"
  website = "https://www.eclipse.org"
  email = "chris.guindon@eclipse-foundation.org"
  facebook = "eclipse.org"
  twitter = "EclipseFdn"
  youtube = "EclipseFdn"
  googleplus = "+Eclipse"
  linkedin = "company/eclipse-foundation/"

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1